server {
    listen 80;
    server_name localhost;
    root /var/www/html/public;

    index index.php index.html;

# Proxy semua request Vite
    location ^~ /@vite/ {
        proxy_pass http://host.docker.internal:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location ^~ /resources/ {
        proxy_pass http://host.docker.internal:5173;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

        location ~* \.(jpg|jpeg|png|gif|ico|css|js|svg|woff|ttf|eot|woff2)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }


    location ~ /\.ht {
        deny all;
    }
}
    